### ISSUE TITLE
Missing build in bintray

### ISSUE THREAD

**Issue by tomanders** [ItemConsulting/wsutil-server#3]
Hi, after the release of XP 7.6 our code that uses your lib quit working, with an error-message of: 

Uncaught TypeError: eWs is not a constructor

I was hoping on trying to upgrade to 2.0.0 to see if this solved the problem, but it doesn't seem to be available on: https://dl.bintray.com/pdrevland/wsUtil/no/item/wsUtil/wsUtil/

**Comment by tajakobsen** [comment]
Since Bintray closed this packages are available on [Jitpack](https://jitpack.io/#no.item/lib-xp-wsutil)
